baseURL = 'https://diogoleal.com'
languageCode = 'en-us'
title = 'Diogo Leal'
theme = 'paper'
dateFmt = "02-12-2006"

[menus]
  [[menus.main]]
    name = 'home'
    url = '/'
    identifier = 'home'
    weight = 1
  [[menus.main]]
    name = 'about'
    url = '/about/'
    weight = 2

[params]
  [params.author]
    email = 'diogo@diogoleal.com'
    name = 'Diogo Leal'
